### ISSUE TITLE
大佬，有直接使用的二进制文件吗？

### ISSUE THREAD

**Issue by ghost** [expiron/customized-openwrt#1]

**Comment by expiron** [comment]
感谢关注！
[Azure Pipelines](https://dev.azure.com/expiron/CustomizedOpenWRT/_build/latest?definitionId=22&branchName=master) 仓库中有每日构建，可在[Artifacts](https://dev.azure.com/expiron/CustomizedOpenWRT/_build/results?buildId=1222&view=artifacts&type=publishedArtifacts)中下载编译好的固件。固件仅包含了默认的软件包，如需其他软件包可从https://downloads.openwrt.org/snapshots/packages/mipsel_24kc （对应SNAPSHOT版）下载。

**Comment by expiron** [comment]
由于游客用户只能下载Artifacts全部内容，无法选择只下载固件，将固件上传至此：
[openwrt-18.06-snapshot-r7960-ab9d1bf608-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip](https://github.com/expiron/customized-openwrt/files/4045848/openwrt-18.06-snapshot-r7960-ab9d1bf608-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip)
[openwrt-18.06-snapshot-r7960-ab9d1bf608-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip](https://github.com/expiron/customized-openwrt/files/4045849/openwrt-18.06-snapshot-r7960-ab9d1bf608-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip)
[openwrt-19.07-snapshot-r10867-fd28ef59db-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip](https://github.com/expiron/customized-openwrt/files/4045850/openwrt-19.07-snapshot-r10867-fd28ef59db-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip)
[openwrt-19.07-snapshot-r10867-fd28ef59db-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip](https://github.com/expiron/customized-openwrt/files/4045851/openwrt-19.07-snapshot-r10867-fd28ef59db-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip)
[openwrt-snapshot-r11954-7936cb94a9-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip](https://github.com/expiron/customized-openwrt/files/4045852/openwrt-snapshot-r11954-7936cb94a9-ar71xx-generic-tl-wdr6500-v5-squashfs-factory.zip)
[openwrt-snapshot-r11954-7936cb94a9-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip](https://github.com/expiron/customized-openwrt/files/4045853/openwrt-snapshot-r11954-7936cb94a9-ar71xx-generic-tl-wdr6500-v5-squashfs-sysupgrade.zip)

**Comment by ghost** [comment]
感谢
